{"cells":[{"metadata":{},"cell_type":"markdown","source":"I've implemented a very simple agent for the ConnectX problem, but something bizarre is happening within a nested for-loop."},{"metadata":{"_uuid":"d629ff2d2480ee46fbb7e2d37f6b5fab8052498a","_cell_guid":"79c7e3d0-c299-4dcb-8224-4455121ee9b0","trusted":true},"cell_type":"code","source":"from kaggle_environments import make\n\nenv = make(\"connectx\", debug=True)","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"def my_agent(observation, configuration):\n    possible_actions = [i for i in range(7)]\n\n    for my_action in possible_actions:\n        for their_action in possible_actions:\n            my_score = 50\n            their_score = 100\n            print(f\"{my_action}, {their_action}: my score {my_score}, their score {their_score}\")\n\n    return 1","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Above is the simple agent designed only to reproduce the issue. Below, I'm running my agent against a random-choice agent. While running, notice the outer loop only makes it about half way through `my_action = 4`. In other words, when I run this code, I see lines starting with \n```\n3, 3: my score ...\n3, 4: my score ...\n3, 5: my score ...\n3, 6: my score ... \n4, 0: my score ...\n4, 1: my 0, 0: my score\n```\n\nWhat is happening here and why doesn't the outer loop make it through 4 (and 5 and 6 for that matter)? "},{"metadata":{"trusted":true},"cell_type":"code","source":"env.reset()\nenv.run([my_agent, \"random\"])","execution_count":null,"outputs":[]}],"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"pygments_lexer":"ipython3","nbconvert_exporter":"python","version":"3.6.4","file_extension":".py","codemirror_mode":{"name":"ipython","version":3},"name":"python","mimetype":"text/x-python"}},"nbformat":4,"nbformat_minor":4}